version: '3.3'
volumes:
  pg_data:
  frontend:
  static:
  media:

services:
  db:
    image: postgres:16
    env_file: .env
    hostname: foodgram_pg
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: rukiqq/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/backend/collected_static/
      - media:/backend/media/
    environment:
      WAIT_HOSTS: foodgram_pg:5432
  frontend:
    image: rukiqq/foodgram_frontend
    volumes:
      - frontend:/app/result_build/build/
  nginx:
    image: rukiqq/foodgram_gateway
    depends_on:
      - frontend
      - backend
    ports:
      - "10000:80"
    volumes:
      - frontend:/var/www/frontend/
      - static:/var/html/static/
      - media:/var/html/media/
