# Generated by Django 4.2.10 on 2024-03-19 20:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_ingredient_options_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Цвет",
            ),
        ),
    ]
