# Generated by Django 4.2.10 on 2024-03-27 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientquantity",
            name="amount",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Количество ингредиента в рецепте не может быть < 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, "Количество ингредиента в рецепте не может быть > 32000."
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Время приготовления рецепта не может быть < 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, "Время приготовления рецепта не может быть > 32000."
                    ),
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriterecipes",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"),
                name="recipes_favoriterecipes_unique_relationships",
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"),
                name="recipes_shoppingcart_unique_relationships",
            ),
        ),
    ]
