# Generated by Django 4.2.10 on 2024-03-19 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_following_followrelationship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="following",
                through="users.FollowRelationship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
