# Generated by Django 4.2.10 on 2024-03-20 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_followrelationship_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="followrelationship",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
